### ISSUE TITLE
TemplateDoesNotExist: drf-yasg2/redoc.html

### ISSUE THREAD

**Issue by marcosox** [JoelLefkowitz/drf-yasg#7]
When trying to open the `/docs/` url in my project, Django cannot find the template and the static files, because the app is called `drf-yasg2`, but the template and statics folders have the old `drf-yasg` name:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/src/drf-yasg2/src/drf_yasg/renderers.py", line 75, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg2/redoc.html
```

Renaming the folders:
- `/src/drf-yasg2/src/drf_yasg/templates/drf_yasg` --> `/src/drf-yasg2/src/drf_yasg/templates/drf_yasg2`
- `/src/drf-yasg2/src/drf_yasg/static/drf_yasg` --> `/src/drf-yasg2/src/drf_yasg/static/drf_yasg2`

works as a temporary fix.

**Comment by JoelLefkowitz** [comment]
This is now fixed and merged into release-1.18
